{
  "sudo": "enabled",
  "compiler": "gcc",
  "language": "cpp",
  "before_install": [
    "pip install --user cpp-coveralls",
    "sudo apt-get install lcov",
    "mkdir gtest",
    "cd gtest",
    "git clone https://github.com/google/googletest.git",
    "cd googletest/googletest",
    "export GTEST_DIR=$(pwd)",
    "cd make",
    "make",
    "cd ../../../.."
  ],
  "script": [
    "make clean",
    "make",
    "./TicTacToeBoardTest"
  ],
  "group": "stable",
  "dist": "trusty",
  "os": "linux",
  "after_success": [
    "lcov --directory . --capture --output-file coverage.info",
    "lcov --remove coverage.info '/usr/*' --output-file coverage.info",
    "secret:A65YdaGlJwLKqmhDucW5+bKGKZfOancQGaM1tu1uvjpyk9E/8SLSOAB2KbBXWUYuMYc1meFzER8rG8Y7TLfORQndBx3SIQbHkNtM1mH4rnYQ3Hp/B3SmMPUuXbmbima+4MjpCSPlBGtxojGWJm5FtgrA51XJ4VspNNsNd6BQlt4="
  ]
}

