{
  "sudo": "enabled",
  "compiler": "gcc",
  "language": "cpp",
  "before_install": [
    "pip install --user cpp-coveralls",
    "mkdir gtest",
    "cd gtest",
    "git clone https://github.com/google/googletest.git",
    "cd googletest/googletest",
    "export GTEST_DIR=$(pwd)",
    "cd make",
    "make",
    "cd ../../../.."
  ],
  "script": [
    "make clean",
    "./configure --enable-gcov",
    "make",
    "./TicTacToeBoardTest"
  ],
  "group": "stable",
  "dist": "trusty",
  "os": "linux",
  "after_success": [
    "coveralls --exclude lib --exclude tests --gcov-options '\-b'"
  ]
}

