sudo: enabled

compiler: gcc

language: cpp

before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get install lcov
  - mkdir gtest
  - cd gtest
  - git clone https://github.com/google/googletest.git
  - cd googletest/googletest
  - export GTEST_DIR=$(pwd)
  - cd make
  - make
  - cd ../../../..

script:
  - make clean
  - make
  - ./TicTacToeBoardTest

group: stable

dist: trusty

os: linux

after_success:
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info
  - bash <(curl -s https://codecov.io/bash) -t c3891982-dd51-4a76-9aef-b5310f85e95e
  - coveralls --build-root build --gcov-options '\-balp\' \
      -e build/external \
      -e build/include \
      -e TicTacToeBoardTest.cpp
     
